# Railway Project Configuration
# https://docs.railway.app/deploy/railway-toml-reference

[[services]]
name = "backend"
source = "backend/"

[services.build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate && npm run build"

[services.deploy]
startCommand = "node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
source = "frontend/"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[services.deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
